package entities

type PlayerType string

const (
	AnonymousPlayer  PlayerType = "anonymous"
	RegisteredPlayer PlayerType = "registered"
)

type PlayerSkins string

const (
	SkinDefault PlayerSkins = "default"
)

type Position struct {
	X float64 `json:"x"`
	Z float64 `json:"z"`
}

type Penguin struct {
	Id           string     `json:"id"`
	PlayerSecret string     `json:"player_secret"` //Temporary secret generated by client for authentication
	Type         PlayerType `json:"type"`
	Skin         string     `json:"skin"`
	Position     Position   `json:"position"`
	Mass         float64    `json:"mass"`
	Accel        float64    `json:"accel"`      //Latest acceleration
	Velocity     float64    `json:"velocity"`   //Latest velocity
	Direction    float64    `json:"direction"`  //in degrees (0-360)
	Eliminated   int        `json:"eliminated"` //Round number the player was eliminated in.
}

type PenguinMove struct {
	Direction float64 `json:"direction"` //in degrees (0-360)
	Power     int     `json:"power"`     // Levels of power (2,4,6,8,10)
}
